Repository telos-projects/fish-25, pull requests merged in 2022-04, with the labels that each got.

#3 :memo: README 업데이트
  README.md
Labels: DOCS

#6 :memo: README 업데이트
  README.md
Labels: DOCS

#7 :art: 클라이언트 프로젝트 구축
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/next-env.d.ts
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/public/favicon.ico
  client/public/vercel.svg
  client/styles/Home.module.css
  client/styles/globals.css
  client/tsconfig.json
  client/yarn.lock
Labels: FEATURE

#13 ✨ 문서 업데이트 (#8, #9, #10, #11)
  README.md
  docs/CODE_OF_CONDUCT.adoc
  docs/fish-25.png
  docs/kotlin-code-style.xml
Labels: 문서, 오타, 공통

#15 :fire: fish-25/docs 파일 명 일관성 있게 수정
  README.md
  docs/FISH_25.png
  docs/KOTLIN_CODE_STYLE.xml
Labels: 문서, 오타, 공통

#22 📝 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
  .github/ISSUE_TEMPLATE/PROPOSTION_REPORT.yaml
  .github/ISSUE_TEMPLATE/TODO_REPORT.yaml
Labels: 문서

#24 v0.0.2
  .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
  .github/ISSUE_TEMPLATE/PROPOSTION_REPORT.yaml
  .github/ISSUE_TEMPLATE/TODO_REPORT.yaml
  README.md
  docs/CODE_OF_CONDUCT.adoc
  docs/FISH_25.png
  docs/KOTLIN_CODE_STYLE.xml
Labels: 배포

#29 ✨ Dockerfile 작성
  infra/docker/README.md
  infra/docker/cilent/Dockerfile
  infra/docker/cilent/deploy.sh
  infra/docker/server/Dockerfile
  infra/docker/server/deploy.sh
Labels: 공통, 인프라
